//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horarios()
        {
            this.Reservas = new List<Reservas>();
        }
    
        public int ID_Horario { get; set; }
        public Nullable<int> ID_Ruta { get; set; }
        public Nullable<int> ID_Bus { get; set; }
        public Nullable<int> ID_Conductor { get; set; }
        public string Dia_Semana { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public Nullable<System.TimeSpan> Hora_Llegada { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Conductores Conductores { get; set; }
        public virtual Rutas Rutas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Reservas> Reservas { get; set; }
    }
}
