//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Tickets = new List<Ticket>();
        }
    
        public int ID_Reserva { get; set; }
        public Nullable<int> ID_Horario { get; set; }
        public Nullable<int> ID_Pasajero { get; set; }
        public Nullable<int> Numero_Asientos_Reservados { get; set; }
        public string Estado_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha_Reserva { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Ticket> Tickets { get; set; }
    }
}
