//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class servicioEntities : DbContext
    {
        public servicioEntities()
            : base("name=servicioEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buses> Buses { get; set; }
        public virtual DbSet<Conductores> Conductores { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Pasajeros> Pasajeros { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    
        public virtual ObjectResult<string> ObtenerCedulaConductor(Nullable<int> conductor_id)
        {
            var conductor_idParameter = conductor_id.HasValue ?
                new ObjectParameter("conductor_id", conductor_id) :
                new ObjectParameter("conductor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ObtenerCedulaConductor", conductor_idParameter);
        }
    }
}
