//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Ticket { get; set; }
        public Nullable<int> ID_Reserva { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Estado_Pago { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
